### PR TITLE
KMtoMiles.html

### LINKED ISSUE #15: want to add javascript program
I made a  javascript program to convert KM to Miles, which I would like to add to you repo.

### PR DESCRIPTION
**Pull request by sanskarmalkhede**
A javascript program to convert KM to Miles.

### CODE REVIEW

**Comment by URVESH1121** [comment]
First, you have to create an issue with a proper description. then I will assign issue with `hacktoberfest` label. after that you have to make pull request then If the changes are ok then I will merge your PR with `hacktoberfest-accepted `  label.

**Comment by sanskarmalkhede** [comment]
sure

**Comment by URVESH1121** [comment]
Done👍

**Comment by sanskarmalkhede** [comment]
Thank You 💯

**Pull request merged**
